# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-28 01:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cate',
            name='job',
        ),
        migrations.DeleteModel(
            name='Cate',
        ),
    ]
