# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-28 01:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_cate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cate',
            name='catethree',
        ),
        migrations.RemoveField(
            model_name='cate',
            name='catetwo',
        ),
    ]
