# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-28 03:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_auto_20180928_0151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='cate',
            new_name='cate1',
        ),
        migrations.AddField(
            model_name='job',
            name='cate2',
            field=models.CharField(default=django.utils.timezone.now, max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='cate3',
            field=models.CharField(default=django.utils.timezone.now, max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='cate4',
            field=models.CharField(default=django.utils.timezone.now, max_length=45),
            preserve_default=False,
        ),
    ]
