# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-28 03:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_auto_20180928_0318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='cate1',
        ),
        migrations.RemoveField(
            model_name='job',
            name='cate2',
        ),
        migrations.RemoveField(
            model_name='job',
            name='cate3',
        ),
        migrations.RemoveField(
            model_name='job',
            name='cate4',
        ),
    ]
